//
//  ResourceModels.swift
//  RSSReader
//
//  Created by Izzat on 11/17/18.
//  Copyright (c) 2018 Izzat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Resource {
    // MARK: Use cases
    
    enum RssResource {
        struct Request {
            let urlString: String
            let name: String
            let logoUrlString: String?
        }
        struct Response {
            var url: String
            var title: String
            var logoUrl: URL?
            var error: String?
        }
        struct ViewModel {
            let title: String
            let logoUrl: URL?
            let urlString: String
            let error: String?
        }
    }
}
