//
//  ResourceRouter.swift
//  RSSReader
//
//  Created by Izzat on 11/17/18.
//  Copyright (c) 2018 Izzat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ResourceRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ResourceDataPassing {
    var dataStore: ResourceDataStore? { get }
}

class ResourceRouter: NSObject, ResourceRoutingLogic, ResourceDataPassing {
    weak var viewController: ResourceViewController?
    var dataStore: ResourceDataStore?
}
