//
//  ResourceWorker.swift
//  RSSReader
//
//  Created by Izzat on 11/17/18.
//  Copyright (c) 2018 Izzat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift
import FeedKit

class ResourceAPIWorker {
    func chackRssResource(url: URL) -> Observable<Resource.RssResource.Response> {
        return Observable.create{ observer in
            let parser = FeedParser(URL: url)
            parser.parseAsync {(result) in
                guard let rssFeed = result.rssFeed else {
                    observer.onError(result.error!)
                    observer.on(.completed)
                    return
                }
                if let title = rssFeed.title {
                    let response = Resource.RssResource.Response(url: url.absoluteString, title: title, logoUrl: rssFeed.image?.url)
                    observer.onNext(response)
                    observer.on(.completed)
                } else {
                    
                }
            }
            return Disposables.create()
            }.subscribeOn(ConcurrentDispatchQueueScheduler(qos: .background))
    }
}
