//
//  ResourcePresenter.swift
//  RSSReader
//
//  Created by Izzat on 11/17/18.
//  Copyright (c) 2018 Izzat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ResourcePresentationLogic {
    func presentRssResource(response: Resource.RssResource.Response)
    func presentError(response: Resource.RssResource.Response)
}

class ResourcePresenter: ResourcePresentationLogic {
    
    weak var viewController: ResourceDisplayLogic?
    
    // MARK: Do something
    
    func presentError(response: Resource.RssResource.Response) {
        let viewModel = Resource.RssResource.ViewModel(title: response.title, logoUrl: response.logoUrl, urlString: response.url, error: response.error)
        viewController?.displayError(viewModel: viewModel)
    }
    
    func presentRssResource(response: Resource.RssResource.Response) {
        let viewModel = Resource.RssResource.ViewModel(title: response.title, logoUrl: response.logoUrl, urlString: response.url, error: response.error)
        viewController?.displayRssResource(viewModel: viewModel)
    }
}
