//
//  DetailModels.swift
//  RSSReader
//
//  Created by Izzat on 11/19/18.
//  Copyright (c) 2018 Izzat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FeedKit

enum Detail {
    enum Item {
        struct Response {
            let item: RSSFeedItem?
        }
        struct ViewModel {
            var title: NSAttributedString?
            var description: String?
            var imageUrl: String?
            var pubDate: String?
            var link: String?
            var error: String?
        }
    }
}
