//
//  DetailPresenter.swift
//  RSSReader
//
//  Created by Izzat on 11/19/18.
//  Copyright (c) 2018 Izzat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic {
    func presentItem(response: Detail.Item.Response)
}

class DetailPresenter: DetailPresentationLogic {
    weak var viewController: DetailDisplayLogic?
    
    func presentItem(response: Detail.Item.Response) {
        guard let item = response.item else {
            var viewModel = Detail.Item.ViewModel()
            viewModel.error = "Ой! Что то пошло не так"
            viewController?.displayError(viewModel: viewModel)
            return
        }
        var viewModel = Detail.Item.ViewModel()
        let title = item.title ?? ""
        let attribute = NSMutableAttributedString(string: title)
        let range = (title as NSString).range(of: title)
        attribute.addAttribute(NSAttributedString.Key.backgroundColor, value: #colorLiteral(red: 0.9674748778, green: 0.5865281224, blue: 0.1175738797, alpha: 1), range: range)
        viewModel.title = attribute
        viewModel.imageUrl = item.enclosure?.attributes?.url
        viewModel.description = item.description ?? ""
        viewModel.link = item.link
        if let date = item.pubDate {
            let dateFormatterPrint = DateFormatter()
            dateFormatterPrint.dateFormat = "HH:mm (dd MMM yyyy)"
            viewModel.pubDate = dateFormatterPrint.string(from: date)
        }
        viewController?.displayItem(viewModel: viewModel)
    }
}
