//
//  DetailInteractor.swift
//  RSSReader
//
//  Created by Izzat on 11/19/18.
//  Copyright (c) 2018 Izzat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FeedKit

protocol DetailBusinessLogic {
    func getItem()
}

protocol DetailDataStore {
    var item: RSSFeedItem? { get set }
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore {
    var item: RSSFeedItem?
    
    var presenter: DetailPresentationLogic?
    
    func getItem() {
        let response = Detail.Item.Response(item: item)
        presenter?.presentItem(response: response)
    }
}
