//
//  DetailViewController.swift
//  RSSReader
//
//  Created by Izzat on 11/19/18.
//  Copyright (c) 2018 Izzat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Kingfisher

protocol DetailDisplayLogic: class {
    func displayItem(viewModel: Detail.Item.ViewModel)
    func displayError(viewModel: Detail.Item.ViewModel)
}

class DetailViewController: UIViewController, DetailDisplayLogic {
    
    var interactor: DetailBusinessLogic?
    var router: (NSObjectProtocol & DetailDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = DetailInteractor()
        let presenter = DetailPresenter()
        let router = DetailRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    @IBOutlet weak var imageView: UIImageView!
    @IBOutlet weak var titleLabel: UILabel!
    @IBOutlet weak var descriptionLabel: UILabel!
    @IBOutlet weak var dateLabel: UILabel!
    
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        interactor?.getItem()
    }
    
    func displayItem(viewModel: Detail.Item.ViewModel) {
        let title = viewModel.item?.title ?? ""
        self.title = title
        let attribute = NSMutableAttributedString(string: title)
        let range = (title as NSString).range(of: title)
        attribute.addAttribute(NSAttributedString.Key.backgroundColor, value: #colorLiteral(red: 0.9674748778, green: 0.5865281224, blue: 0.1175738797, alpha: 1), range: range)
        titleLabel.attributedText = attribute
        descriptionLabel.text = viewModel.item?.description ?? ""
        
        let dateFormatterPrint = DateFormatter()
        dateFormatterPrint.dateFormat = "HH:mm (dd MMM yyyy)"
        
        guard let date = viewModel.item?.pubDate else {
            return
        }
        dateLabel.text = dateFormatterPrint.string(from: date)
        if let urlString = viewModel.item?.enclosure?.attributes?.url,
            let url = URL(string: urlString) {
            let imageResource = ImageResource(downloadURL: url)
            imageView.kf.setImage(with: imageResource, placeholder: Image(named: "picture"))
        }
    }
    
    func displayError(viewModel: Detail.Item.ViewModel) {
        let alert = UIAlertController(title: "Ошибка", message: viewModel.error!, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "Ok", style: .default, handler: nil))
        present(alert, animated: true, completion: nil)
    }
}
