//
//  MainPresenter.swift
//  RSSReader
//
//  Created by Izzat on 11/16/18.
//  Copyright (c) 2018 Izzat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic {
    func presentFeed(response: Main.Feed.Response)
    func presentFeeds(response: Main.Feeds.Response)
    func presentError(response: Main.Errors.Response)
    func deleteFeed(response: Main.Feed.Delete)
    func routeToSourceVC()
}

class MainPresenter: MainPresentationLogic {
    weak var viewController: MainDisplayLogic?
    
    func presentFeed(response: Main.Feed.Response) {
        let viewModel = Main.Feed.ViewModel(rssFeed: response.feed)
        viewController?.displayFeed(viewModel: viewModel)
    }
    
    func presentFeeds(response: Main.Feeds.Response) {
        let viewModel = Main.Feeds.ViewModel(feeds: response.feeds)
        viewController?.displayFeeds(viewModel: viewModel)
    }
    
    func presentError(response: Main.Errors.Response) {
        let viewModel = Main.Errors.ViewModel(message: response.message)
        viewController?.displayError(viewModel: viewModel)
    }
    
    func deleteFeed(response: Main.Feed.Delete) {
        let viewModel = Main.Feed.Delete(url: response.url)
        viewController?.deleteFeed(viewModel: viewModel)
    }
    
    func routeToSourceVC() {
        viewController?.routToSourceVC()
    }
}
