//
//  ResourceRouter.swift
//  RSSReader
//
//  Created by Izzat on 11/17/18.
//  Copyright (c) 2018 Izzat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SourceDataPassing {
    var dataStore: SourceDataStore? { get }
}

class SourceRouter: NSObject, SourceDataPassing {
    weak var viewController: SourceViewController?
    var dataStore: SourceDataStore?
}
