//
//  ResourceViewController.swift
//  RSSReader
//
//  Created by Izzat on 11/17/18.
//  Copyright (c) 2018 Izzat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Kingfisher

protocol SourceDisplayLogic: class {
    func displayRssResource(viewModel: Source.RssSource.ViewModel)
    func displayRssResources(viewModel: [Source.RssSource.ViewModel])
    func displayError(viewModel: Source.Errors.ViewModel)
}

class SourceViewController: UITableViewController, SourceDisplayLogic {
    
    private var resources = [Source.RssSource.ViewModel]()
    private var interactor: SourceBusinessLogic?
    var router: (NSObjectProtocol & SourceDataPassing)?
    
    @IBOutlet weak var textField: UITextField!
    @IBOutlet weak var indicator: UIActivityIndicatorView!
    @IBOutlet weak var addButton: UIButton!
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = SourceInteractor()
        let presenter = SourcePresenter()
        let router = SourceRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        interactor?.getAllResources()
    }
    
    @IBAction func addButton(_ sender: UIButton) {
        addButton.isHidden = true
        indicator.startAnimating()
        let request = Source.RssSource.Request(urlString: textField.text ?? "", title: "", logoUrlString: "")
        interactor?.addRssResource(request: request)
    }
    
    func displayRssResources(viewModel: [Source.RssSource.ViewModel]) {
        resources = viewModel
        tableView.reloadData()
    }
    
    func displayRssResource(viewModel: Source.RssSource.ViewModel) {
        indicator.stopAnimating()
        addButton.isHidden = false
        textField.text = nil
        resources.insert(viewModel, at: 0)
        tableView.insertRows(at: [IndexPath(row: 0, section: 0)], with: .bottom)
    }
    
    func displayError(viewModel: Source.Errors.ViewModel) {
        indicator.stopAnimating()
        addButton.isHidden = false
        let alert = UIAlertController(title: "Ошибка", message: viewModel.message, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "Ok", style: .default, handler: nil))
        present(alert, animated: true, completion: nil)
    }
}

extension SourceViewController {
    override func tableView(_ tableView: UITableView, titleForHeaderInSection section: Int) -> String? {
        return resources.count > 0 ? "Источники" : nil
    }
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return resources.count
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "resourceCell", for: indexPath)
        let resource = resources[indexPath.item]
        cell.textLabel?.text = resource.title
        if let urlString = resource.logoUrl,
            let url = URL(string: urlString) {
            let imageResource = ImageResource(downloadURL: url)
            let processor = ResizingImageProcessor(referenceSize: CGSize(width: 39, height: 39), mode: .aspectFit)
            cell.imageView?.kf.setImage(with: imageResource, placeholder: Image(named: "ic_rss")?.withRenderingMode(.alwaysTemplate), options: [.processor(processor)])
        } else {
            cell.imageView?.image = Image(named: "ic_rss")?.withRenderingMode(.alwaysTemplate)
        }
        return cell
    }
    
    override func tableView(_ tableView: UITableView, canEditRowAt indexPath: IndexPath) -> Bool {
        return true
    }
    
    override func tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath) -> [UITableViewRowAction]? {
        let deleteAction = UITableViewRowAction(style: .destructive, title: "Удалить", handler: {[weak self] (action, indexPath) in
            guard let _self = self else {return}
            let resource = _self.resources[indexPath.row]
            _self.resources.remove(at: indexPath.row)
            tableView.deleteRows(at: [indexPath], with: .bottom)
            let request = Source.RssSource.Request(urlString: resource.urlString, title: resource.title, logoUrlString: resource.logoUrl)
            _self.interactor?.deleteRssResource(request: request)
        })
        return [deleteAction]
    }
}

