//
//  ResourcePresenter.swift
//  RSSReader
//
//  Created by Izzat on 11/17/18.
//  Copyright (c) 2018 Izzat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SourcePresentationLogic {
    func presentRssResource(response: Source.RssSource.Response)
    func presentError(response: Source.Errors.Response)
    func presentRssResources(response: Source.RssSources.Response)
}

class SourcePresenter: SourcePresentationLogic {

    weak var viewController: SourceDisplayLogic?
    
    func presentError(response: Source.Errors.Response) {
        let viewModel = Source.Errors.ViewModel(message: response.message)
        viewController?.displayError(viewModel: viewModel)
    }
    
    func presentRssResource(response: Source.RssSource.Response) {
        let viewModel = Source.RssSource.ViewModel(title: response.title, logoUrl: response.logoUrl, urlString: response.url)
        viewController?.displayRssResource(viewModel: viewModel)
    }
    
    func presentRssResources(response: Source.RssSources.Response) {
        var viewModel = [Source.RssSource.ViewModel]()
        for rssChannel in response.rssChannels {
            if let title = rssChannel.name,
                let url = rssChannel.url {
                viewModel.append(Source.RssSource.ViewModel(title: title, logoUrl: rssChannel.logo_url, urlString: url))
            }
        }
        viewController?.displayRssResources(viewModel: viewModel)
    }
}
