//
//  MainRouter.swift
//  RSSReader
//
//  Created by Izzat on 11/16/18.
//  Copyright (c) 2018 Izzat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainRoutingLogic {
    func routeToResourceVC(segue: UIStoryboardSegue?)
}

protocol MainDataPassing {
    var dataStore: MainDataStore? { get }
}

class MainRouter: NSObject, MainRoutingLogic, MainDataPassing {
    weak var viewController: MainViewController?
    var dataStore: MainDataStore?
    
    // MARK: Routing
    
    func routeToResourceVC(segue: UIStoryboardSegue?) {
      if let segue = segue {
        let destinationVC = segue.destination as! SourceViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
      }
    }
    
    // MARK: Passing data
    
    func passDataToSomewhere(source: MainDataStore, destination: inout SourceDataStore) {
      destination.mainDelegate = source.mainDelegate
    }
}
